bot-options:
  # Server ip
  host: localhost

  # Default Minecraft servers port is 25565. Set this only if server has different port
  port: 25565

  # Bot should select a Minecraft version automatically, but if you want specific,
  # set this on your own
  version: 1.20.4

  # Set this to your email for Minecraft account or to username for offline-mode servers
  username: MySuperUsername

  # Set this only if you use Minecraft account
  # password: ''

  # Only set this if you are using Microsoft account and then set this to 'microsoft'
  # auth: 'mojang'

bot-commands:
  # If you want to disable bot commands, set this to false

  # !!! Command 'config' with 'set' subcommand require system permission
  # to write to this file !!!
  enabled: true

  # Prefix for bot commands. Must be set, otherwise bot commands won't work.
  # If you will want to send message on server that starts with this prefix,
  # just add \ before.
  prefix: '-'


chat:
  # Messages to ignore. Filter uses RegExp match
  ignored-messages: []

  logs:
    # If logs should be enabled. This function saves every message to file and when you open online
    # panel, displays every mesasge from file on site.
    # !!! This require system permission for write to file logs.log !!!
    enabled: true

    # Type of saved messages limit.
    # count - while adding new message to file, every old message that is over the limit count
    # will be deleted
    # time - while adding new message, every old message that is older than limit, will be deleted
    # infinity - stored messages won't be deleted. Be aware with this setting cause with a lot
    # of saved data log file can be large
    limit-type: 'time'

    # Limit for saved messages. According to the selected type:
    # count - limit in messages count
    # time - limit in minutes
    # infinity - limit doesn't matter
    limit: 2880 # 2880 minutes - 2 days


on-join:
  # Messages/commands to send on join. It's like in console or online panel, if you start message with
  # bot command prefix, then bot command will be executed. If you start message with slash (/),
  # Minecraft command will be executed and if you write just message, this message will be send on chat.

  # Pattern:
  # <timeout>:<message>
  # Timeout is counting in miliseconds after join event

  commands:
    # Some examples:
    # - '500:/login mYsUpErSeCrEtPaSsWoRd123'
    # - '1000:Hello everyone!'
    # - '5000:/home'
    # - '5500:/panel'
    # - '6000:-inv leftclick 5'


auto-rejoin:
  # Whether bot should rejoin to server when it gets kicked out
  enabled: true

  # Time in seconds before bot again join server
  timeout: 15


online-panel:
  # If you want to disable online panel, set this to false
  enabled: true


  # Port for online panel, default is 3000
  port: 3000

  # Prefixed for messages in the panel
  message-prefixes:
    # Available variables:
    # {years}, {months}, {days},
    # {hours}, {minutes}, {seconds}

    # Minecraft messages - chat, commands etc.
    minecraft: '§7[{hours}:{minutes}:{seconds}] §r'
    # Bot internal messages
    bot: '§7[{hours}:{minutes}:{seconds}] §f§l[BOT] §r'

  # Messages to load from log file to show in online panel when you open it
  last-messages:
    # Limit type:
    # count - max messages count
    # time - max messages age in minutes
    # all - will load all messages from the log file
    type: 'count'

    # Limit value.
    limit: 2000
  
  features:
    player-list:
      # How often player list is updated. In milliseconds
      interval: 50